---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer-claim
  labels:
    app: peer-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "ibmc-file-gold"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org-ca-claim
  labels:
    app: org-ca-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "ibmc-file-gold"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-claim
  labels:
    app: couchdb-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "ibmc-file-gold"
